In [ ]:
# No. 1
import numpy as np
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [ ]:
# No.2
import numpy as np
b = np.random.randint(0,10,size=(4,3))
print(b)

[[4 4 2]
 [2 4 0]
 [5 6 6]
 [7 2 9]]


In [ ]:
# No. 3
import numpy as np
c = np.zeros((2,2))
d = np.ones((2,2))
print(c)
print(d)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]


In [ ]:
# No. 4
import numpy as np
e = np.array([[1,2,3,4,5,6],
 [7,8,9,10,11,12],
  [13,14,15,16,17,18]])
eTranspo = e.T
print(e)
print(eTranspo)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
[[ 1  7 13]
 [ 2  8 14]
 [ 3  9 15]
 [ 4 10 16]
 [ 5 11 17]
 [ 6 12 18]]


In [ ]:
# No. 5
import numpy as np
n = 3
p = 4
m = 5

f = np.random.randint(0,10,size=(n,p))
g = np.random.randint(0,10,size=(p,m))

dotProduct = np.dot(f,g)
print(f)
print(g)
print(dotProduct)

[[0 8 7 3]
 [4 7 8 3]
 [5 4 9 1]]
[[1 6 3 7 6]
 [0 0 1 5 6]
 [6 4 6 1 5]
 [3 4 3 1 3]]
[[ 51  40  59  50  92]
 [ 61  68  76  74 115]
 [ 62  70  76  65 102]]
